import {test,after} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID} from 'node:crypto';
const dir=mkdtempSync(join(tmpdir(),'capsule-tests-'));process.env.LOCAL_DB_PATH=join(dir,'test.sqlite');process.env.DATA_BACKEND='local';process.env.NODE_ENV='test';
const {db,transaction,reserveLocal}=await import('../lib/local.js');const store=await import('../lib/store.js');const {createFor,openFor}=await import('../lib/service.js');const {hashPassword,checkPassword}=await import('../lib/crypto.js');const {registerSchema,capsuleSchema,reflectionSchema}=await import('../lib/validation.js');
const alice=randomUUID(),bob=randomUUID();db().prepare('INSERT INTO users VALUES(?,?,?,?)').run(alice,'alice@example.test','Alice','unused');db().prepare('INSERT INTO users VALUES(?,?,?,?)').run(bob,'bob@example.test','Bob','unused');
const input=()=>({title:'A letter from today',message:'This is a private message, not public.',opensAt:new Date(Date.now()+3600000).toISOString(),password:'CapsulePass123!',confirm:'CapsulePass123!',ack:'yes'});
after(()=>{db().close();rmSync(dir,{recursive:true,force:true});});
test('Argon2id uses random salts and verifies only correct passwords',async()=>{const a=await hashPassword('same-password'),b=await hashPassword('same-password');assert.match(a,/^\$argon2id\$/);assert.notEqual(a,b);assert(await checkPassword(a,'same-password'));assert(!await checkPassword(a,'wrong'));});
test('validation rejects confirmation mismatch and invalid values',()=>{assert(!registerSchema.safeParse({name:'a',email:'bad',password:'short',confirm:'no'}).success);assert(!capsuleSchema.safeParse({...input(),confirm:'wrong'}).success);assert(!capsuleSchema.safeParse({...input(),ack:''}).success);assert(!reflectionSchema.safeParse({body:'x'}).success);});
test('creation is atomic and metadata excludes message and hash',async()=>{const id=await createFor(alice,input()),c=await store.getCapsule(alice,id);assert.equal(c.title,input().title);assert(!('message' in c));assert(!('password_hash' in c));assert.equal(await store.content(id),input().message);assert.match(await store.secret(id),/^\$argon2id\$/);assert.deepEqual((await store.listCapsules(bob)),[]);});
test('cannot create capsule with past date',async()=>{await assert.rejects(()=>createFor(alice,{...input(),opensAt:new Date(Date.now()-1000).toISOString()}),/อนาคต/);});
test('correct password never overrides release time or ownership',async()=>{const id=await createFor(alice,input());await assert.rejects(()=>openFor(alice,id,input().password),/ยังไม่ถึงเวลา/);await assert.rejects(()=>openFor(bob,id,input().password),/ไม่มีสิทธิ์/);assert.equal(await store.getCapsule(bob,id),null);});
test('wrong password fails; five attempts lock even correct password',async()=>{const id=await createFor(alice,input());db().prepare('UPDATE capsules SET opens_at=? WHERE id=?').run(new Date(Date.now()-1000).toISOString(),id);for(let i=0;i<5;i++)await assert.rejects(()=>openFor(alice,id,'wrong-pass'),/ไม่ถูกต้อง/);await assert.rejects(()=>openFor(alice,id,input().password),/15 นาที/);assert.equal((await store.getCapsule(alice,id)).opened_at,null);});
test('lock expires and every later read requires password',async()=>{const id=await createFor(alice,input());db().prepare('UPDATE capsules SET opens_at=? WHERE id=?').run(new Date(Date.now()-1000).toISOString(),id);await assert.rejects(()=>openFor(alice,id,'wrong-pass'));assert.equal(await openFor(alice,id,input().password),input().message);const stamp=(await store.getCapsule(alice,id)).opened_at;assert(stamp);await assert.rejects(()=>openFor(alice,id,'wrong-pass'),/ไม่ถูกต้อง/);await openFor(alice,id,input().password);assert.equal((await store.getCapsule(alice,id)).opened_at,stamp);});
test('rate limiter reserves atomically and expires',()=>{assert.equal(Array.from({length:10},()=>reserveLocal('parallel')).filter(Boolean).length,5);db().prepare('UPDATE attempts SET reset_at=? WHERE key=?').run(Date.now()-1,'parallel');assert(reserveLocal('parallel'));});
test('delete checks owner and cascades all private data',async()=>{const id=await createFor(alice,input());await store.writeReflection(id,'reflection text');await store.removeRecord(bob,id);assert(await store.getCapsule(alice,id));await store.removeRecord(alice,id);assert.equal(await store.getCapsule(alice,id),null);assert.equal(await store.secret(id),undefined);assert.equal(await store.content(id),undefined);assert.equal(await store.getReflection(id),null);});
test('rollback leaves no partial capsule',()=>{const id=randomUUID();assert.throws(()=>transaction(d=>{d.prepare('INSERT INTO capsules VALUES(?,?,?,?,?,NULL)').run(id,alice,'partial',new Date().toISOString(),new Date().toISOString());throw new Error('failure');}));assert.equal(db().prepare('SELECT * FROM capsules WHERE id=?').get(id),undefined);});

const email=await import('../lib/email.js');
const current={id:alice,email:'alice@example.test'};
function challenge(id,purpose='reset',expiry=Date.now()+600000){db().prepare('INSERT OR REPLACE INTO email_challenges VALUES(?,?,?,?,?)').run(id,purpose,alice,email.codeDigest(id,purpose,'12345678'),expiry);}
test('recovery rejects wrong owner, wrong code, expiry, and replay; preserves opening date',async()=>{
 const id=await createFor(alice,input());challenge(id);const date=(await store.getCapsule(alice,id)).opens_at;
 await assert.rejects(()=>email.confirmCode({id:bob},id,'reset','12345678','NewPassword123!','NewPassword123!'));
 await assert.rejects(()=>email.confirmCode(current,id,'reset','00000000','NewPassword123!','NewPassword123!'));
 challenge(id,'reset',Date.now()-1);await assert.rejects(()=>email.confirmCode(current,id,'reset','12345678','NewPassword123!','NewPassword123!'));
 challenge(id);await email.confirmCode(current,id,'reset','12345678','NewPassword123!','NewPassword123!');
 assert(await checkPassword(await store.secret(id),'NewPassword123!'));assert(!await checkPassword(await store.secret(id),input().password));
 assert.equal((await store.getCapsule(alice,id)).opens_at,date);await assert.rejects(()=>openFor(alice,id,'NewPassword123!'),/ยังไม่ถึงเวลา/);
 await assert.rejects(()=>email.confirmCode(current,id,'reset','12345678','OtherPass123!','OtherPass123!'));
});
test('verification attempt limit survives new codes',async()=>{const id=await createFor(alice,input());challenge(id,'notify');for(let n=0;n<5;n++)await assert.rejects(()=>email.confirmCode(current,id,'notify','00000000'));challenge(id,'notify');await assert.rejects(()=>email.confirmCode(current,id,'notify','12345678'),/15 นาที/);});
test('notifications only send verified due capsules, retry failures, then skip sent records',async()=>{
 const future=await createFor(alice,input()),due=await createFor(alice,input());
 challenge(future,'notify');challenge(due,'notify');await email.confirmCode(current,future,'notify','12345678');await email.confirmCode(current,due,'notify','12345678');
 db().prepare('UPDATE capsules SET opens_at=? WHERE id=?').run(new Date(Date.now()-1000).toISOString(),due);
 const savedFetch=globalThis.fetch;process.env.RESEND_API_KEY='test';process.env.EMAIL_FROM='test@example.test';process.env.APP_URL='http://localhost:3000';let bodies=[];
 try{globalThis.fetch=async()=>({ok:false});assert.deepEqual(await email.sendDue(),{sent:0,failed:1});globalThis.fetch=async(url,options)=>{bodies.push(JSON.parse(options.body));assert.equal(options.headers['Idempotency-Key'],`capsule-ready-${due}`);return {ok:true};};assert.deepEqual(await email.sendDue(),{sent:1,failed:0});assert.deepEqual(await email.sendDue(),{sent:0,failed:0});assert.equal(bodies.length,1);assert(!bodies[0].text.includes(input().message));assert.equal(bodies[0].to[0],current.email);}finally{globalThis.fetch=savedFetch;delete process.env.RESEND_API_KEY;delete process.env.EMAIL_FROM;delete process.env.APP_URL;}
});
test('missing email configuration does not pretend to send a code',async()=>{const id=await createFor(alice,input());await assert.rejects(()=>email.requestCode(current,id,'reset'),/ตั้งค่า/);});
