"use client";
import {useActionState,useState,useTransition} from 'react';import {LockKeyhole,CalendarDays,PenLine,ArrowUpRight} from 'lucide-react';import {createCapsule} from '@/app/actions';import {Field,Password,Feedback,Submit} from './FormBits';import Art from './Art';
import { encryptE2EE } from '@/lib/cryptoClient';
import { useUIStore } from '@/lib/storeClient';
const prompts={exam:{title:'ถึงฉัน… หลังสอบไฟนอล',message:'ถึงตัวฉันหลังสอบไฟนอล\n\nวันนี้ฉันรู้สึก…'},graduate:{title:'ถึงฉัน… ในวันเรียนจบ',message:'ถึงตัวฉันในวันเรียนจบ\n\nความฝันที่ฉันอยากฝากไว้คือ…'}};
function localDate(date){const d=new Date(date.getTime()-date.getTimezoneOffset()*60000);return d.toISOString().slice(0,16);}
export default function CreateForm({prompt}){const initial=prompts[prompt]||{};const [state,action,isPending]=useActionState(createCapsule,{});const [values,setValues]=useState({title:initial.title||'',message:initial.message||'',date:'',password:'',confirm:''});const [ack,setAck]=useState(false);const [isEncrypting, setIsEncrypting] = useState(false);const change=e=>setValues({...values,[e.target.name]:e.target.value});const iso=values.date&&!Number.isNaN(Date.parse(values.date))?new Date(values.date).toISOString():'';
const showToast = useUIStore(s => s.showToast); const pending = isPending || isEncrypting;
const submitForm = (e) => { e.preventDefault(); const fd = new FormData(e.target); if (values.message.length < 10) return; showToast('กำลังเข้ารหัสข้อความขั้นสูง (E2EE)...'); setIsEncrypting(true); encryptE2EE(values.password, values.message).then(({ payload, authHash }) => { fd.set('message', payload); fd.set('password', authHash); fd.set('confirm', authHash); import('react').then(React => { React.startTransition(() => action(fd)); setIsEncrypting(false); }); }).catch(err => { showToast('เกิดข้อผิดพลาดในการเข้ารหัส: ' + err.message); setIsEncrypting(false); }); };
return <div className="editor-layout"><form onSubmit={submitForm} className="paper-panel"><div className="panel-heading"><span className="panel-dot"/><span>NEW_MEMORY.txt</span><span className="window-buttons">− □ ×</span></div><div className="editor-body"><Feedback state={state}/><fieldset disabled={pending}><div className="form-section-heading"><span>01</span><h2>อยากบอกอะไรกับตัวเอง?</h2><PenLine size={18}/></div><Field name="title" label="ชื่อแคปซูล" error={state.fields?.title}><input id="title" name="title" placeholder="เช่น ถึงฉันในวันที่กล้ากว่าเดิม" value={values.title} onChange={change} required minLength={2} maxLength={80}/></Field><Field name="message" label="ข้อความถึงตัวเองในอนาคต" error={state.fields?.message}><textarea id="message" name="message" rows={9} placeholder="ถึงตัวฉันในวันข้างหน้า…
วันนี้มีเรื่องอยากเล่าให้ฟัง" value={values.message} onChange={change} required minLength={10} maxLength={10000}/><span className="character-count">{values.message.length.toLocaleString()} / 10,000</span></Field><div className="form-section-heading"><span>02</span><h2>กลับมาเจอกันเมื่อไหร่ดี?</h2><CalendarDays size={18}/></div><Field name="date" label="วันและเวลาเปิดแคปซูล" error={state.fields?.opensAt} hint="เลือกตามเวลาบนอุปกรณ์ของคุณ ระบบจะบันทึกเป็นเวลาเดียวกันทั่วโลก"><input id="date" name="date" type="datetime-local" value={values.date} onChange={change} required/></Field><input type="hidden" name="opensAt" value={iso}/><div className="date-presets">{[[2,'อีก 2 นาที'],[1440,'พรุ่งนี้'],[43200,'อีก 30 วัน'],[525600,'อีก 1 ปี']].map(([minutes,label])=><button key={minutes} type="button" onClick={()=>setValues({...values,date:localDate(new Date(Date.now()+minutes*60000))})}>{label}</button>)}</div><div className="form-section-heading"><span>03</span><h2>เก็บไว้ให้คุณคนเดียว</h2><LockKeyhole size={18}/></div><div className="two-fields"><Field name="password" label="รหัสผ่านแคปซูล" error={state.fields?.password}><Password name="password" value={values.password} onChange={change} error={state.fields?.password}/></Field><Field name="confirm" label="ยืนยันรหัสผ่านแคปซูล" error={state.fields?.confirm}><Password name="confirm" value={values.confirm} onChange={change} error={state.fields?.confirm}/></Field></div><p className="field-hint">แนะนำให้ใช้รหัสผ่านต่างจากบัญชีของคุณ และจดจำไว้ให้ดี</p><label className="check-label"><input type="checkbox" name="ack" value="yes" checked={ack} onChange={e=>setAck(e.target.checked)} required/><span>ฉันเข้าใจว่าปิดผนึกแล้วจะแก้ข้อความหรือวันเปิดไม่ได้ หากลืมรหัสผ่าน ต้องยืนยันผ่านอีเมลของบัญชีเพื่อตั้งรหัสใหม่</span></label>{state.fields?.ack&&<p className="field-error">{state.fields.ack}</p>}<Submit pending={pending}>ปิดผนึก แล้วส่งถึงอนาคต <ArrowUpRight size={19}/></Submit></fieldset></div></form><aside className="editor-aside"><div className="preview-card"><span className="eyebrow">A SNEAK PEEK OF YOUR MEMORY</span><Art small/><h3>{values.title||'ความทรงจำบทใหม่ของคุณ'}</h3><div className="preview-date">{values.date?new Date(values.date).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'}):'เลือกวันนัดพบกับตัวเอง'}</div><span className="status-badge"><LockKeyhole size={12}/> เปิดเมื่อถึงเวลาเท่านั้น</span></div><div className="writing-tips"><span className="tip-star">✧</span><h3>เขียนแบบที่เป็นคุณ</h3><p>วันนี้อะไรทำให้ยิ้ม?<br/>กำลังพยายามเพื่ออะไรอยู่?<br/>อยากขอบคุณตัวเองเรื่องไหน?</p><p>ไม่ต้องสมบูรณ์แบบ แค่จริงใจก็พอ ♡</p></div></aside></div>;}
