"use client";
import {useActionState,useState,useEffect} from 'react';import Link from 'next/link';import {LockKeyhole,Heart,ArrowRight} from 'lucide-react';import {openCapsule} from '@/app/actions';import {Field,Password,Feedback,Submit} from './FormBits';import Art from './Art';
import { hashPasswordForServer, decryptE2EE } from '@/lib/cryptoClient';
import { useUIStore } from '@/lib/storeClient';
function UnlockBody({capsule}){const [state,action,isPending]=useActionState(openCapsule.bind(null,capsule.id),{});const [password,setPassword]=useState('');const [decrypted,setDecrypted]=useState(null);const [isDecrypting, setIsDecrypting]=useState(false);const showToast=useUIStore(s=>s.showToast);const pending=isPending||isDecrypting;
useEffect(()=>{if(state.opened&&state.message){setIsDecrypting(true);decryptE2EE(password,state.message).then(plaintext=>{setDecrypted(plaintext);setIsDecrypting(false);}).catch(e=>{showToast('ถอดรหัสล้มเหลว รหัสผ่านอาจไม่ถูกต้อง');setIsDecrypting(false);});}},[state.opened,state.message]);
const submitForm=(e)=>{e.preventDefault();const fd=new FormData(e.target);showToast('กำลังตรวจสอบกุญแจ...');setIsDecrypting(true);hashPasswordForServer(password).then(authHash=>{fd.set('password',authHash);import('react').then(React=>{React.startTransition(()=>action(fd));setIsDecrypting(false);});}).catch(err=>{showToast('เกิดข้อผิดพลาด: '+err.message);setIsDecrypting(false);});};
if(state.opened&&decrypted)return <section className="opened-memory"><div className="open-celebration" aria-hidden="true">✦ <Heart/> ✦</div><span className="eyebrow">A MESSAGE THAT FINALLY FOUND YOU</span><h2>ข้อความจากตัวคุณในวันนั้น ♡</h2><article className="letter"><span className="letter-date">DEAR FUTURE ME,</span><p>{decrypted}</p><span className="letter-signature">ด้วยรัก จากฉันในอดีต ♡</span></article><div className="after-open"><p>อ่านแล้วรู้สึกยังไงบ้าง? เก็บความรู้สึกของวันนี้ไว้อีกหน่อยไหม</p><Link className="button" href={`/capsules/${capsule.id}/reflection`}>เขียนความรู้สึกของวันนี้ <ArrowRight size={18}/></Link></div></section>;
return <div className="unlock-box"><span className="unlock-icon"><LockKeyhole size={25}/></span><h2>ถึงเวลาของความทรงจำแล้ว!</h2><p>ใส่รหัสผ่านแคปซูล แล้วไปพบตัวเองในวันนั้นกัน</p><form onSubmit={submitForm}><Feedback state={state}/><fieldset disabled={pending}><Field name="password" label="รหัสผ่านแคปซูล"><Password name="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="off"/></Field><Submit pending={pending}>{isDecrypting?'กำลังไขกุญแจเข้ารหัสลับ...':'เปิดแคปซูลของฉัน ♡'}</Submit></fieldset></form><small>ทุกครั้งที่เปิดอ่านข้อความ ต้องยืนยันรหัสผ่านใหม่</small></div>;}
export default function Unlock({capsule}){const [epoch,setEpoch]=useState(0);useEffect(()=>{const clear=()=>setEpoch(v=>v+1);const hidden=()=>{if(document.visibilityState==='hidden')clear();};window.addEventListener('pagehide',clear);document.addEventListener('visibilitychange',hidden);return()=>{window.removeEventListener('pagehide',clear);document.removeEventListener('visibilitychange',hidden);};},[]);return <UnlockBody key={epoch} capsule={capsule}/>;}
