import { createClient } from '@supabase/supabase-js';
import { db, transaction, reserveLocal } from './local.js';
export const remote=()=>process.env.DATA_BACKEND==='supabase';
export function supabase(admin=true){
 const url=process.env.SUPABASE_URL,key=admin?process.env.SUPABASE_SERVICE_ROLE_KEY:process.env.SUPABASE_ANON_KEY;
 if(!url||!key)throw new Error('ยังตั้งค่า Supabase ไม่ครบ กรุณาตรวจไฟล์ .env.local');
 return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
}
function unwrap({data,error}){if(error)throw new Error('เชื่อมต่อฐานข้อมูลไม่สำเร็จ กรุณาลองอีกครั้ง');return data;}
export async function listCapsules(owner){if(remote())return unwrap(await supabase().from('capsules').select('id,title,created_at,opens_at,opened_at').eq('owner_id',owner).order('created_at',{ascending:false}));return db().prepare('SELECT id,title,created_at,opens_at,opened_at FROM capsules WHERE owner_id=? ORDER BY created_at DESC').all(owner).map(row=>({...row}));}
export async function getCapsule(owner,id){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id))return null;if(remote())return unwrap(await supabase().from('capsules').select('id,title,created_at,opens_at,opened_at').eq('owner_id',owner).eq('id',id).maybeSingle());const row=db().prepare('SELECT id,title,created_at,opens_at,opened_at FROM capsules WHERE owner_id=? AND id=?').get(owner,id);return row?{...row}:null;}
export async function createRecord(c,message,passwordHash){if(remote())return unwrap(await supabase().rpc('create_capsule',{p_id:c.id,p_owner:c.owner_id,p_title:c.title,p_opens:c.opens_at,p_message:message,p_hash:passwordHash}));transaction(d=>{d.prepare('INSERT INTO capsules(id,owner_id,title,created_at,opens_at) VALUES(?,?,?,?,?)').run(c.id,c.owner_id,c.title,c.created_at,c.opens_at);d.prepare('INSERT INTO capsule_contents VALUES(?,?)').run(c.id,message);d.prepare('INSERT INTO capsule_secrets VALUES(?,?)').run(c.id,passwordHash);});}
export async function secret(id){if(remote())return unwrap(await supabase().from('capsule_secrets').select('password_hash').eq('capsule_id',id).single()).password_hash;return db().prepare('SELECT password_hash FROM capsule_secrets WHERE capsule_id=?').get(id)?.password_hash;}
export async function content(id){if(remote())return unwrap(await supabase().from('capsule_contents').select('message').eq('capsule_id',id).single()).message;return db().prepare('SELECT message FROM capsule_contents WHERE capsule_id=?').get(id)?.message;}
export async function markOpened(id){if(remote()){unwrap(await supabase().from('capsules').update({opened_at:new Date().toISOString()}).eq('id',id).is('opened_at',null));return;}db().prepare('UPDATE capsules SET opened_at=COALESCE(opened_at,?) WHERE id=?').run(new Date().toISOString(),id);}
export async function getReflection(id){if(remote())return unwrap(await supabase().from('reflections').select('body,updated_at').eq('capsule_id',id).maybeSingle());const row=db().prepare('SELECT body,updated_at FROM reflections WHERE capsule_id=?').get(id);return row?{...row}:null;}
export async function writeReflection(id,body){if(remote()){unwrap(await supabase().from('reflections').upsert({capsule_id:id,body,updated_at:new Date().toISOString()}));return;}db().prepare('INSERT INTO reflections VALUES(?,?,?) ON CONFLICT(capsule_id) DO UPDATE SET body=excluded.body,updated_at=excluded.updated_at').run(id,body,new Date().toISOString());}
export async function removeRecord(owner,id){if(remote()){unwrap(await supabase().from('capsules').delete().eq('owner_id',owner).eq('id',id));return;}db().prepare('DELETE FROM capsules WHERE id=? AND owner_id=?').run(id,owner);}
export async function reserveAttempt(key,limit=5){if(remote())return unwrap(await supabase().rpc('reserve_attempt',{p_key:key,p_limit:limit}));return reserveLocal(key,limit);}
export async function resetAttempts(key){if(remote()){unwrap(await supabase().from('attempts').delete().eq('key',key));return;}db().prepare('DELETE FROM attempts WHERE key=?').run(key);}
